# Generated by Django 3.2.8 on 2024-09-10 11:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MST_Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MST_Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('grade', models.IntegerField()),
                ('remarks', models.CharField(editable=False, max_length=10)),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_grades.mst_subject')),
            ],
        ),
    ]
