# Generated by Django 3.2.8 on 2024-09-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mst_student',
            name='student_key',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mst_subject',
            name='subject_key',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
